### PR TITLE
vernemq: introduce vernemq 1.12.5

### PR DESCRIPTION
**Pull request by joaohf**

### CODE REVIEW

**Comment by joaohf** [comment]
Hello.

Sure, I can. Usually I also added init.d too. Could you, if possible, share
an init.d reference script ?



Em qua, 4 de mai de 2022 11:11 AM, tvroegop ***@***.***>
escreveu:

**Comment by tvroegop** [comment]
The following script will do.

```
#! /bin/sh

NAME=vernemq
VERNECTL=/usr/lib/vernemq/bin/vernemq
SCRIPTNAME=/etc/init.d/$NAME

#
# Function that starts the vernemq service
#
do_start()
{
    # Return
    #   0 if vernemq has been started
    #   1 if vernemq was already running
    #   2 if vernemq could not be started
    $VERNECTL start

    local RC=$?
    if [ $RC -gt 1 -o $RC -lt 0 ]; then
        return 2;
    fi

    return $RC
}

#
# Function that stops the vernemq service
#
do_stop()
{
    # Return
    #   0 if vernemq has been stopped
    #   1 if vernemq was already stopped
    #   other if a failure occurred
    $VERNECTL stop
}

#
# Function that graceful reload the vernemqi service
#
do_reload() {
    # Return
    #   0 if vernemq has been restarted
    #   1 if vernemq was not started in the first place
    #   other if a failure occurred
    $VERNECTL restart
}

# Checks the status of vernemq service
do_status() {
    $VERNECTL ping > /dev/null && echo $"$NAME is running" && return 0
    echo $"$NAME is stopped" && return 2
}

case "$1" in
    start)
        echo -n "Starting $NAME "
        do_start
        case "$?" in
            0|1) exit 0 ;;
            2) exit 1 ;;
        esac
        ;;
    stop)
        echo -n "Stopping $NAME "
        do_stop
        case "$?" in
            0|1) exit 0 ;;
            *) exit 1 ;;
        esac
        ;;
    status)
        do_status
        ;;
    reload|force-reload)
        echo -n "Reloading $NAME "
        do_reload
        ES=$?
        exit $ES
        ;;
    restart)
        echo -n "Restarting $NAME "
        do_stop
        case "$?" in
            0|1)
                do_start
                case "$?" in
                    0)  exit 0 ;;
                    1)  exit 1 ;; # Old process is still running
                    *)  exit 1 ;; # Failed to start
                esac
                ;;
            *)
                # Failed to stop
                exit 1
                ;;
        esac
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|force-reload}" >&2
        exit 3
        ;;
esac
```

**Review by tvroegop — COMMENTED** [review]
The folder /var/log/vernemq is not created when DISTRO_FEATURES does not contain systemd

**Comment by joaohf** [comment]
Hi,

When using systemv. There is another file that creates the /var/log. I'll
fix that too.

Thanks

Em sex, 6 de mai de 2022 10:16 AM, tvroegop ***@***.***>
escreveu:

**Comment by joaohf** [comment]
Hello @tvroegop 

I've added the init script and also fixed the /var/log/vernemq folder.

**Comment by tvroegop** [comment]
Hi @joaohf,

One other thing I noticed was that I need to also run the epmd process in order to use vernemq. There is an epmd.init script in the epmd recipe, but that one is never installed when I build an image with vernemq. Erlang, including epmd is being built and installed as a dependency of vernemq though. The do_install() step of epmd should also be run I would think. Or is it because I'm not building vernemq correctly? I'm adding vernemq recipe to

IMAGE_INSTALL_append = " packagegroup-core-boot packagegroup-core-full-cmdline-mcgraw vernemq"

**Comment by joaohf** [comment]
Hello

The epmd recipe is not installed. It exists only if you want to use/control
the epmd by yourself.

I use to install vernemq as you did. And epmd is started automatically (the
epmd from vernemq release, because rebar3 release creates an erlang release
with all included).

I have to run and take a close look too. When testing vernemq I saw the
epmd process being started. You can check as well using the 'ps' and trying
to get the full epmd daemon path. It should point to /usr/lib/vernemq/...

One thing that I alway do when starting vernemq is to change the hostname.
But this is more linux system configuration.

PS: I'll need a bit more time due some appointments.

Em qui, 12 de mai de 2022 7:26 AM, tvroegop ***@***.***>
escreveu:

**Comment by joaohf** [comment]
Hi @tvroegop 

I've updated the recipe, removed the unnecessary RDEPENDS requirements. When testing, do not forget to set the host name like using FQDN names.

**Comment by joaohf** [comment]
Hi, I'm merging it right now. Feel free to open any issue later.

**Comment by tvroegop** [comment]
Thank you, much appreciated!

**Pull request merged**
